imgs = {
    "announce": "bot/database/images/announce.png",
    "armor": "bot/database/images/armor.png",
    "bastards": "bot/database/images/bastards.jpg",
    "boo": "bot/database/images/boo.png",
    "drake": "bot/database/images/drake.jpg",
    "electro": "bot/database/images/electro.png",
    "fact": "bot/database/images/fact.jpg",
    "fbi": "bot/database/images/fbi.jpg",
    "google": "bot/database/images/google.png",
    "monster": "bot/database/images/monster.jpg",
    "patrick": "bot/database/images/patrick.jpg",
    "prison": "bot/database/images/prison.png",
    "santa": "bot/database/images/santa.jpg",
    "shit": "bot/database/images/shit.jpg",
    "slap": "bot/database/images/slap.jpg",
    "smile": "bot/database/images/smile.jpg",
    "spongebob": "bot/database/images/spongebob.png",
    "sword": "bot/database/images/sword.jfif",
    "unplug": "bot/database/images/unplug.jpg",
    "worthless": "bot/database/images/worthless.jpg",
}
